version: '3.4'

services:
  game:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: 'postgres:14'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo
    volumes:
      - data:/var/lib/postgresql/data

volumes:
    data: