version: '3.4'

services:
  game:
    build: .
    ports:
      - '1234:1234'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - back
  back:
    build: ./backend
    ports:
      - '3333:3333'
    volumes:
      - ./backend/:/backend
      - /backend/node_modules
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "tibia"
      TZ: America/Sao_Paulo
    volumes:
        - ./db/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
        - ./db/dml.sql:/docker-entrypoint-initdb.d/dml.sql
    expose: 
        - "5433"
    ports:
      - "5433:5433"
    command: -p 5433